system: 
  name: Edwiges
  port: 3000
slack: 
  bot:
    name: edwiges
    token: no_token
    icon: ':edwiges:'
  push_channel: comunicacao-gitlab-teste
  mr_channel: comunicacao-gitlab-teste
  clrPush: '#fb6c25'
  clrOpen: '#36a64f'
  clrUpdate: '#3019ff'
  clrMerge: '#16c8c6'
  clrNotAssigned: '#dd111f'
  clrWarning: '#dd1207'
gitlab:
  events: 
    - Push Hook
    - Note Hook
    - Pipeline Hook
    - Merge Request Hook
  url: https://edwiges-bot.herokuapp.com/webhook
  token: MX4Jg6UooHWkEhCtXsCpGoL1d5qntYeA